---
-
  name: Update Chro binary
  hosts:
    - all
  become: yes
  tasks:
    ## update & upgrade system
    - name: Update & upgrade system
      apt:
        upgrade: yes
        update_cache: yes

    ## stop chro service
    - name: Stop chro service
      systemd:
        state: stopped
        name: chro

    ## get the latest release
    - name: Get latest release link
      uri:
        url: https://api.github.com/repos/0xPolygon/polygon-edge/releases/latest
        return_content: true
      register: edge_release

    ## download the latest release
    - name: Download latest Chro release
      get_url:
        url: "{{ edge_release.json.assets[3].browser_download_url }}"
        dest: /tmp/chro.tar.gz
        force: yes

    ## create temp dir for release
    - name: Create temp dir for Chro release
      file:
        path: /tmp/chro
        state: directory

    ## unpack release tar
    - name: Unpack Chro release
      unarchive:
        remote_src: yes
        src: /tmp/chro.tar.gz
        dest: /tmp/chro

    ## set chro to PATH
    - name: Place Chro binary to PATH
      copy:
        remote_src: yes
        src: /tmp/chro/chro
        dest: /usr/local/bin/
        mode: a+x
        force: yes

    ## remove release temp dir
    - name: Remove temp Chro release dir
      file:
        state: absent
        path: /tmp/chro

    ## start chro service
    - name: Start chro service
      systemd:
        state: restarted
        name: chro
        daemon_reload: yes
        enabled: yes